# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(530, 376))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_ZoomIn = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Image/resources/icons8-zoom-in-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZoomIn.setIcon(icon)
        self.pushButton_ZoomIn.setCheckable(False)
        self.pushButton_ZoomIn.setAutoRepeat(False)
        self.pushButton_ZoomIn.setAutoExclusive(True)
        self.pushButton_ZoomIn.setAutoRepeatDelay(100)
        self.pushButton_ZoomIn.setAutoRepeatInterval(50)
        self.pushButton_ZoomIn.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.pushButton_ZoomIn.setAutoRaise(True)
        self.pushButton_ZoomIn.setObjectName("pushButton_ZoomIn")
        self.horizontalLayout_2.addWidget(self.pushButton_ZoomIn)
        self.pushButton_ZoomOut = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Image/resources/icons8-zoom-out-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZoomOut.setIcon(icon1)
        self.pushButton_ZoomOut.setCheckable(False)
        self.pushButton_ZoomOut.setAutoRepeat(False)
        self.pushButton_ZoomOut.setAutoExclusive(True)
        self.pushButton_ZoomOut.setAutoRaise(True)
        self.pushButton_ZoomOut.setObjectName("pushButton_ZoomOut")
        self.horizontalLayout_2.addWidget(self.pushButton_ZoomOut)
        self.pushButton_ResetZoom = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Image/resources/icons8-zoom-to-actual-size-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ResetZoom.setIcon(icon2)
        self.pushButton_ResetZoom.setAutoRepeat(False)
        self.pushButton_ResetZoom.setAutoExclusive(True)
        self.pushButton_ResetZoom.setAutoRaise(True)
        self.pushButton_ResetZoom.setObjectName("pushButton_ResetZoom")
        self.horizontalLayout_2.addWidget(self.pushButton_ResetZoom)
        self.pushButton_Select = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Image/resources/icons8-cursor-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Select.setIcon(icon3)
        self.pushButton_Select.setCheckable(True)
        self.pushButton_Select.setAutoRepeat(False)
        self.pushButton_Select.setAutoExclusive(True)
        self.pushButton_Select.setAutoRaise(True)
        self.pushButton_Select.setObjectName("pushButton_Select")
        self.horizontalLayout_2.addWidget(self.pushButton_Select)
        self.pushButton_Move = QtWidgets.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Image/resources/icons8-move-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Move.setIcon(icon4)
        self.pushButton_Move.setCheckable(True)
        self.pushButton_Move.setChecked(True)
        self.pushButton_Move.setAutoRepeat(False)
        self.pushButton_Move.setAutoExclusive(True)
        self.pushButton_Move.setAutoRaise(True)
        self.pushButton_Move.setObjectName("pushButton_Move")
        self.horizontalLayout_2.addWidget(self.pushButton_Move)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Image/resources/icons8-accuracy-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon5)
        self.toolButton_3.setCheckable(True)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Image/resources/icons8-hunt-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon6)
        self.toolButton.setCheckable(True)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Image/resources/icons8-polygon-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon7)
        self.toolButton_2.setCheckable(True)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.view_TargetImage = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(self.view_TargetImage.sizePolicy().hasHeightForWidth())
        self.view_TargetImage.setSizePolicy(sizePolicy)
        self.view_TargetImage.setMinimumSize(QtCore.QSize(200, 200))
        self.view_TargetImage.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.view_TargetImage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.view_TargetImage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.view_TargetImage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.view_TargetImage.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.view_TargetImage.setSceneRect(QtCore.QRectF(0.0, 0.0, 45.0, 40.0))
        self.view_TargetImage.setRenderHints(QtGui.QPainter.TextAntialiasing)
        self.view_TargetImage.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
        self.view_TargetImage.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.view_TargetImage.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.view_TargetImage.viewport().setProperty("cursorSelect", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.view_TargetImage.viewport().setProperty("cursorMove", QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.view_TargetImage.setObjectName("view_TargetImage")
        self.gridLayout.addWidget(self.view_TargetImage, 1, 1, 1, 1)
        self.tree_HitPoints = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_HitPoints.setMinimumSize(QtCore.QSize(100, 200))
        self.tree_HitPoints.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tree_HitPoints.setMouseTracking(False)
        self.tree_HitPoints.setAutoFillBackground(False)
        self.tree_HitPoints.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tree_HitPoints.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tree_HitPoints.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tree_HitPoints.setDragEnabled(True)
        self.tree_HitPoints.setAlternatingRowColors(False)
        self.tree_HitPoints.setObjectName("tree_HitPoints")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_HitPoints)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Object/resources/icons8-folder-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon8)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_HitPoints)
        item_0.setIcon(0, icon8)
        self.tree_HitPoints.header().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tree_HitPoints, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        self.Menu = QtWidgets.QMenu(self.menubar)
        self.Menu.setObjectName("Menu")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/File/resources/icons8-opened-folder-50-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon9)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/File/resources/icons8-save-50-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon10)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/File/resources/icons8-save-as-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon11)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/File/resources/icons8-close-window-50-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon12)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/File/resources/icons8-file-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon13)
        self.actionNew.setObjectName("actionNew")
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setCheckable(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Object/resources/icons8-back-arrow-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBack.setIcon(icon14)
        self.actionBack.setObjectName("actionBack")
        self.actionForward = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Object/resources/icons8-forward-button-50-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForward.setIcon(icon15)
        self.actionForward.setObjectName("actionForward")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Object/resources/icons8-add-50-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon16)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Object/resources/icons8-cancel-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon17)
        self.actionDelete.setObjectName("actionDelete")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Object/resources/icons8-edit-50-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon18)
        self.actionEdit.setObjectName("actionEdit")
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Program/resources/icons8-play-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon19)
        self.actionStart.setObjectName("actionStart")
        self.Menu.addAction(self.actionNew)
        self.Menu.addAction(self.actionOpen)
        self.Menu.addSeparator()
        self.Menu.addAction(self.actionSave)
        self.Menu.addAction(self.actionSave_As)
        self.Menu.addSeparator()
        self.Menu.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionStart)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionBack)
        self.menuEdit.addAction(self.actionForward)
        self.menubar.addAction(self.Menu.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionBack)
        self.toolBar.addAction(self.actionForward)

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_Move, self.tree_HitPoints)
        MainWindow.setTabOrder(self.tree_HitPoints, self.view_TargetImage)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_ZoomIn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Zoom in (Ctrl+\'+\')</p></body></html>"))
        self.pushButton_ZoomIn.setText(_translate("MainWindow", "..."))
        self.pushButton_ZoomIn.setShortcut(_translate("MainWindow", "Ctrl++"))
        self.pushButton_ZoomOut.setToolTip(_translate("MainWindow", "<html><head/><body><p>Zoom out (Ctrl+\'-\')</p></body></html>"))
        self.pushButton_ZoomOut.setText(_translate("MainWindow", "..."))
        self.pushButton_ZoomOut.setShortcut(_translate("MainWindow", "Ctrl+_"))
        self.pushButton_ResetZoom.setToolTip(_translate("MainWindow", "<html><head/><body><p>Reset view (Ctrl+0)</p></body></html>"))
        self.pushButton_ResetZoom.setText(_translate("MainWindow", "..."))
        self.pushButton_ResetZoom.setShortcut(_translate("MainWindow", "Ctrl+0"))
        self.pushButton_Select.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select</p></body></html>"))
        self.pushButton_Select.setText(_translate("MainWindow", "..."))
        self.pushButton_Move.setToolTip(_translate("MainWindow", "<html><head/><body><p>Move</p></body></html>"))
        self.pushButton_Move.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.tree_HitPoints.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.tree_HitPoints.headerItem().setText(1, _translate("MainWindow", "Value"))
        __sortingEnabled = self.tree_HitPoints.isSortingEnabled()
        self.tree_HitPoints.setSortingEnabled(False)
        self.tree_HitPoints.topLevelItem(0).setText(0, _translate("MainWindow", "Hit 1"))
        self.tree_HitPoints.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Location"))
        self.tree_HitPoints.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "(3,3)"))
        self.tree_HitPoints.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Score"))
        self.tree_HitPoints.topLevelItem(0).child(1).setText(1, _translate("MainWindow", "5"))
        self.tree_HitPoints.topLevelItem(1).setText(0, _translate("MainWindow", "Hit 2"))
        self.tree_HitPoints.setSortingEnabled(__sortingEnabled)
        self.Menu.setTitle(_translate("MainWindow", "&File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open (Ctrl+O)</p></body></html>"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "Exit"))
        self.actionQuit.setToolTip(_translate("MainWindow", "Quit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionBack.setText(_translate("MainWindow", "Back"))
        self.actionBack.setToolTip(_translate("MainWindow", "Back (Ctrl+Z)"))
        self.actionBack.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionForward.setText(_translate("MainWindow", "Forward"))
        self.actionForward.setToolTip(_translate("MainWindow", "Forward (Ctrl+Y)"))
        self.actionForward.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionAdd.setShortcut(_translate("MainWindow", "Ctrl+Shift++, Ctrl+A"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del, Ctrl+Shift+-"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionEdit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStart.setToolTip(_translate("MainWindow", "Start"))
        self.actionStart.setShortcut(_translate("MainWindow", "Ctrl+P, Space"))
import rsc_rc
